# MD013/line-length : Line length : https://github.com/DavidAnson/markdownlint/blob/vmain/doc/md013.md
MD013:
  # Number of characters
  line_length: 140

# MD028/no-blanks-blockquote : Blank line inside blockquote : https://github.com/DavidAnson/markdownlint/blob/main/doc/md028.md
MD028: false

# MD044/no-inline-html : Inline HTML : https://github.com/DavidAnson/markdownlint/blob/main/doc/md033.md
MD033:
  allowed_elements:
    - details
    - summary
