#!/bin/bash

set -o pipefail
set -o nounset
set -e

# Regenerate web-panel SSH certitificate.

/bin/openssl req -new -newkey rsa:2048 -days 3650 -nodes -x509 -subj "/CN=Eaton" \
    -keyout "${SYNOPKG_PKGDEST}/bin/key.pem" \
    -out "${SYNOPKG_PKGDEST}/bin/cert.pem"

# Write default configuration.

cat > "${SYNOPKG_PKGDEST}/configs/config.js" <<EOF
cfg =
{
  "shutdownSettings":
  {
    "shutdownType": "script",
    "shutdownScript": "${SYNOPKG_PKGDEST}/configs/actions/signal_lb.sh"
  },
  "autoUpdate":
  {
    "checkInterval": -1
  }
}
EOF

chmod 644 "${SYNOPKG_PKGDEST}/configs/config.js"

# Write IPP NUT low battery signal script.

script_file="${SYNOPKG_PKGDEST}/configs/actions/signal_lb.sh"
signal_file="${SYNOPKG_PKGDEST}/lb_timestamp"

cat > "$script_file" <<EOF
#!/bin/bash
date +%s > "$signal_file"
EOF

chmod +x "$script_file"
