#!/bin/bash

PKG_NAME="eaton-ipp"
INST_DIR="/tmp/_${PKG_NAME}"
PKG_DIR="/tmp/_${PKG_NAME}_pkg"
PKG_DEST="/image/packages"

PrepareDirs() {
    for dir in $INST_DIR $PKG_DIR; do
        rm -rf "$dir"
    done
    for dir in $INST_DIR $PKG_DIR $PKG_DEST; do
        mkdir -p "$dir"
    done
}

Install() {
    ( cd package && DESTDIR=${INST_DIR} make install )
    cp -r package/ui/ "${INST_DIR}"
}

GenerateINFO() {
    package/INFO.sh > INFO
    cp INFO "${PKG_DIR}"
}

InstallSynologyConfig(){
    cp -r package/conf/ "${PKG_DIR}"
    cp -r package/scripts/ "${PKG_DIR}"
    cp package/PACKAGE_ICON{,_256}.PNG "${PKG_DIR}"
}

MakePackage() {
    source /pkgscripts/include/pkg_util.sh

    pkg_make_package $INST_DIR $PKG_DIR
    pkg_make_spk $PKG_DIR $PKG_DEST "$(pkg_get_spk_family_name)"
}

main() {
    PrepareDirs
    Install
    GenerateINFO
    InstallSynologyConfig
    MakePackage
}

main "$@"
